site_name: WTFdoc
site_url: https://gaudren.github.io/WTFdoc/
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

plugins:
  - mkdocs-nav-weight
